### PR TITLE
Update 14-3-1-Error-messages.py

### PR DESCRIPTION
**Pull request by umbernhard**
Currently this passive scan script can't run due to a wrong number of parameters error. This fixes that.

### CODE REVIEW

**Comment by BlazingWind** [comment]
Thank you for the raising the issue @umbernhard! 
I've tested the script and found the error happens due to `cweID` being a string instead of an integer. Changing `cweID = "209 and 210"` to `cweID = 209` fixed the error. Changing ` value` to ` value=None` made no difference. Please could you explain the issue that you encountered and how this PR fixes it?

**Comment by umbernhard** [comment]
I can modify the PR to swap out the CWE data type. I was getting a "too many arguments" error and wasn't sure how to fix it, so adding a default parameter to `msg` seemed to at least get the script to run.

**Comment by umbernhard** [comment]
Yeah, I can confirm changing the type of `cweID` does not change the error:
`TypeError: scan() takes exactly 4 arguments (3 given)`

**Comment by BlazingWind** [comment]
I just realized where the error comes from - the script should be run as an active script. I can confirm that I encounter the error when this script is run as a passive script.

A year or two ago I was collaborating with researchers from Yale on scripts and we reorganized the repo. It seems during that time this script fell into the `passive`  folder, although it should have been in the `active` folder.  I assume you ran it as a passive script due to this misplacement. Apologies for the confusion!

The error that I encountered was `TypeError: raiseAlert(): 11th arg can't be coerced to int` when running this script as active script. I'm going to change to cweID to int and move this script to the passive folder. That should fix all the errors.

If you still have issues with this script, feel free to let me know.

**Pull request closed without merging**
